### ISSUE TITLE
Design the shape of the enclosure

### ISSUE THREAD

**Issue by AznStevy** [AznStevy/VariableLight#1]
Create a CAD design for the enclosure.

**Comment by ps178** [comment]
No CAD design uploaded for review

**Comment by AznStevy** [comment]
@ps178 Located here: https://github.com/AznStevy/VariableLight/tree/szx2/develop-mech/Mecahnical 
PR here: https://github.com/AznStevy/VariableLight/pull/14

**Comment by ps178** [comment]
Thank you for the link.
Could you upload the .f3d file?
Also the 2d renderings need to have dimensions on them. I think only Bottom House file has dimensions.
