### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by AznStevy** [AznStevy/VariableLight#10]
The electrical/software stuff is on the master branch. I'm probably not going to move forward with the `more-ambitious` stuff.

**Comment by mlp6** [comment]
Looks good... why abandon the ambitious stuff?  I'm guessing time-limited.

**Comment by AznStevy** [comment]
Definitely time. If I somehow have spare time at the end of the semester/next semester, I'd like to try this. For now, I think something simpler will be plenty to learn.
