### ISSUE TITLE
Finding parts

### ISSUE THREAD

**Issue by AznStevy** [AznStevy/VariableLight#11]
I'm trying to place the necessary parts onto the board using what was given [here](https://github.com/mlp6/Fundamentals-BME-Design/tree/master/Resources/Available-Components). However, when I try to look for it in the explorer/searching, the part doesn't show up such as the arduino connector. I could find the capacitors and resistors, just not the connectors.

**Comment by mlp6** [comment]
Connectors are just going to be discrete male header pins (see my Sakai announcement from this morning); nothing else special.  That translates to holes 0.1 in on center on the board.
