### ISSUE TITLE
Altium Design

### ISSUE THREAD

**Issue by AznStevy** [AznStevy/VariableLight#12]
I've uploaded some related things onto [this](https://github.com/AznStevy/VariableLight/tree/szx2/develop-electrical/Electrical) branch. Honestly no clue if anything is right.

**Comment by sphaerobolus** [comment]
I don't see much other than a hand-drawn sketch. Is it possible that you committed locally but didn't push?

**Comment by AznStevy** [comment]
Should be here https://github.com/AznStevy/VariableLight/blob/szx2/develop-electrical/Electrical/Light_PCB.pdf

**Comment by sphaerobolus** [comment]
Huh. I can follow that link, but I don't find this file under the code tab. @mlp6 what am I doing wrong? 

I am not a big fan of using two components when you really want one. You have two headers to represent the Nano (right @AznStevy?) but I think that should be one part. It's too easy to confuse your reader (pin names?), and even accidentally shove one header relative to the other on the board. And then your Nano doesn't fit. You'll be sad. 

Assuming you're using the Nano, you don't need the voltage regulator. The Nano has a regulator on board. Feed your 9V to the Vin pin and it will regulate it to 5V as needed. You can use the 5V from the 5V pin. (If you want to use a voltage regulator, use a different package. We don't have that package. We do have the TO-220 and TO-92 packages.)

I don't think three LEDs in series will work here. You're driving them with 5V, but the sum of the forward voltages is probably greater than 5V. And I think the 510 Ohm resistor is probably high.

**Comment by AznStevy** [comment]
Hi Matt, thanks for the advice! Yes, I plan to use the Nano. I thought that I would need to manually space out the headers since there are two rows of pins on the Nano. Is there a header that already perfectly fits it? I'll probably take out the regulator like you said, which will make my life easier. I'll look into the LED thing soon as well.

Edit: Additionally, I think the reason why you didn't see the stuff is because I'm doing work on a separate branch and GitHub defaults to master which is currently pretty bare.

**Comment by sphaerobolus** [comment]
There isn't a header per se, but the footprint for the Nano is available as an Eagle library. Easy to find. 

Ah, branches. I should have thought of that.

**Comment by AznStevy** [comment]
Approved in #13
