### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by AznStevy** [AznStevy/VariableLight#6]
I need some help as to how to put this together. My hope was that I could somehow just swap out the resister values in the PWM circuit, but I'm not sure of a good way to do that. I'm also having trouble finding a way to connect the LED of the astable multivibrator with the reset of the circuit. Lastly, I made a logic circuit for the 5-state ring counter, but I'm not sure how this would be compatible with the rest of the circuit...

The schematics are on the `more-ambitious` branch: https://github.com/AznStevy/VariableLight/blob/szx2/more-ambitious/Electrical/Electrical%20Schematic.pdf

**Comment by mlp6** [comment]
Lets add some other folks to this Issue to also chime in (Matt, Petek and Brinnae).  There are several balls in the air with this one.
